dont create release too early

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -49,12 +49,18 @@ on:
 
 jobs:
   create-release:
-    needs: [build, test-publish]
+    needs: [build, run-tests, test-publish]
     runs-on: ubuntu-latest
     outputs:
       releasetag: ${{ steps.currenttag.outputs.tag }}
 
     steps:
+    - name: Check Test Results
+      if: ${{ needs.run-tests.outputs.testresult != 'success' }}
+      run: |
+        echo "Tests failed. Failing the job."
+        exit 1
+
     - name: Checkout
       uses: actions/checkout@v4
       with:
@@ -292,7 +298,7 @@ jobs:
         retention-days: 5
 
   actually_release:
-    needs: [create-release, build, test-publish]
+    needs: [create-release]
     strategy:
       matrix:
         configuration: [Release]
